version: '3'

services:
  db:
    image: postgres
    volumes:
      - /home/db:/var/lib/postgresql/data
  dockertest:
    build: .
    image: micropyramid/django-crm:1
    environment:
      - DJANGO_SETTINGS_MODULE=crm.docker_settings
      - SG_USER="${SG_USER}"
      - SG_PWD="${SG_PWD}"
    ports:
      - "8000"
    depends_on:
      - db